const questions = [
  {
    question: 'What is the capital of France?',
    answers: ['London', 'Paris', 'Rome', 'Madrid'],
    rightAnswer: 'Paris',
    difficult: 1,
    id: 1,
    isOpen: true,
  },
  {
    question: 'Which planet is known as the Red Planet?',
    answers: ['Earth', 'Venus', 'Mars', 'Jupiter'],
    rightAnswer: 'Mars',
    difficult: 2,
    id: 2,
    isOpen: false,
  },
  {
    question: 'What is the largest ocean in the world?',
    answers: ['Atlantic', 'Indian', 'Pacific', 'Arctic'],
    rightAnswer: 'Pacific',
    difficult: 3,
    id: 3,
    isOpen: false,
  },
  {
    question: 'Who was the first man to walk on the moon?',
    answers: [
      'Neil Armstrong',
      'Buzz Aldrin',
      'Michael Collins',
      'Yuri Gagarin',
    ],
    rightAnswer: 'Neil Armstrong',
    difficult: 4,
    id: 4,
    isOpen: false,
  },
  {
    question: 'What is the currency of Japan?',
    answers: ['Yen', 'Euro', 'Dollar', 'Pound'],
    rightAnswer: 'Yen',
    difficult: 5,
    id: 5,
    isOpen: false,
  },
  {
    question: 'Who is the author of Pride and Prejudice?',
    answers: ['Emily Bronte', 'Jane Austen', 'Charles Dickens', 'George Eliot'],
    rightAnswer: 'Jane Austen',
    difficult: 6,
    id: 6,
    isOpen: false,
  },
  {
    question: 'What is the tallest mammal in the world?',
    answers: ['Elephant', 'Giraffe', 'Hippopotamus', 'Rhino'],
    rightAnswer: 'Giraffe',
    difficult: 7,
    id: 7,
    isOpen: false,
  },
  {
    question: 'Who was the first President of the United States?',
    answers: [
      'George Washington',
      'Abraham Lincoln',
      'Thomas Jefferson',
      'Theodore Roosevelt',
    ],
    rightAnswer: 'George Washington',
    difficult: 8,
    id: 8,
    isOpen: false,
  },
  {
    question: 'Who painted the Mona Lisa?',
    answers: [
      'Leonardo da Vinci',
      'Vincent van Gogh',
      'Pablo Picasso',
      'Michelangelo',
    ],
    rightAnswer: 'Leonardo da Vinci',
    difficult: 9,
    id: 9,
    isOpen: false,
  },
  {
    question: 'What is the largest desert in the world?',
    answers: ['Sahara', 'Gobi', 'Arabian', 'Kalahari'],
    rightAnswer: 'Sahara',
    difficult: 10,
    id: 10,
    isOpen: false,
  },
  {
    question: 'Who wrote the Harry Potter series?',
    answers: [
      'J.K. Rowling',
      'George R.R. Martin',
      'Stephen King',
      'Suzanne Collins',
    ],
    rightAnswer: 'J.K. Rowling',
    difficult: 11,
    id: 11,
    isOpen: false,
  },
  {
    question: 'What is the highest mountain in the world?',
    answers: ['Mount Everest', 'K2', 'Kilimanjaro', 'Denali'],
    rightAnswer: 'Mount Everest',
    difficult: 12,
    id: 12,
    isOpen: false,
  },
]

export default questions
